### ISSUE TITLE
wrong dynamic url for news vs practical

### ISSUE THREAD

**Issue by esbenholk** [oskarrough/alivefestival#5]
when we click through to practical.post or type out the url ../praktisk/(exampleFAQpost) we arrive at the correct destination, but when we reload the page, the last written news article appears on the same address

**Comment by oskarrough** [comment]
hey hey, I believe it is because of a typo here, where you load the `post` (e.g. news) model instead of `faq`.

https://github.com/oskarrough/alivefestival/blob/921e035438df38ebebccca28d89fe085271a8b07/app/practical/post/route.js#L4-L8

**Comment by esbenholk** [comment]
Perfekt!
