### ISSUE TITLE
News and FAQ refresh glitch

### ISSUE THREAD

**Issue by esbenholk** [oskarrough/alivefestival#6]
When reloading the page for a News Post or FAQ post, it delivers the first costume type of its kind instead of the post fitting the URL. It must be something with the slug and the new faq costume type: ex. When on "/praktisk/sikkerhed", it refreshes to show the content for "/praktisk/billetter-adgang", but without changing the URL.

**Comment by oskarrough** [comment]
Can you try logging `params.faq_slug`? I think it's undefined. Maybe it is called `params.post_slug` or just `params.slug`?

https://github.com/oskarrough/alivefestival/blob/2020/app/practical/post/route.js#L6

**Comment by esbenholk** [comment]
solved! fixed with the defined slug and writing in models instead of query. 
thank you
